jobs:
- job: VS_Latest
  timeoutInMinutes: 90

  pool:
    vmImage: windows-2019

  steps:
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries') }}:
    - template: .vsts-ci.canaries.yml

  - task: GitVersion@5
    inputs:
      updateAssemblyInfo: false   

# Restore nuget.org to the list of existing sources, .NET 6 Pre 2 may somehow remove it
  - powershell: |
      dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org | Out-Null
      $global:LASTEXITCODE = 0
    displayName: Adjust nuget.org source
    
  - task: MSBuild@1
    displayName: Build Samples
    inputs:
      solution: UI\**\*.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /p:Configuration=Release "/p:InformationalVersion=$(GitVersion.InformationalVersion)" /p:AotAssemblies=false /ds
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
